### ISSUE TITLE
Save subtitles in LocalStorage

### ISSUE THREAD

**Issue by ramasilveyra** [yashagarwal1411/SubtitlesForYoutube#1]
If instead of upload subtitles files to https://subtitles-youtube.herokuapp.com/upload/ saves in LocalStorage (Web Storage)?
Yo can see similar examples of how do that here:
* [Loading webfonts with high performance on responsive websites](http://bdadam.com/blog/loading-webfonts-with-high-performance.html)
* [Storing data in the browser with the HTML5 localStorage API](http://toddmotto.com/storing-data-in-the-browser-with-the-html5-local-storage-api/)

**Comment by yashagarwal1411** [comment]
Done. Now everything happens from javascript.
