### ISSUE TITLE
Amara doesn't work

### ISSUE THREAD

**Issue by walidsa3d** [yashagarwal1411/SubtitlesForYoutube#16]
When the extensionfinds  subtitles in Amara it loads weird stuff about Firefox (I'm using chrome).

**Comment by yashagarwal1411** [comment]
Just confirmed the issue. Its doing the same thing for me. Whats happening is that Amara has changed its API response and its sending information about subtitles for a 'Firefox installation support' video somehow. I'll debug this more and release a fix in 2-3 days. Thanks for notifying.

**Comment by yashagarwal1411** [comment]
Fixed
