### ISSUE TITLE
Options to choose Language Search

### ISSUE THREAD

**Issue by leocaseiro** [yashagarwal1411/SubtitlesForYoutube#21]
Hi, thanks for this amazing app!

I wanted to download Brazilian Portuguese , and using developer tools, I've switched from Chinese to `pob` and it worked great.

I was wondering if would be nice have all languages from open subtitles or perhaps an option to add/remove.

I'm happy to send you a PR, let me know your thoughts.

![screen shot 2016-04-11 at 8 11 39 pm](https://cloud.githubusercontent.com/assets/940070/14423919/a2696b2a-0021-11e6-93f7-e0083eaafcc6.png)

**Comment by yashagarwal1411** [comment]
Hey Thanks for pr. I'll get around to merging it and uploading a new version in 2-3 days.

**Comment by yashagarwal1411** [comment]
Merged and released with V 3.4.19
