### ISSUE TITLE
Subtiles fro Youtube does not work with Chromecast

### ISSUE THREAD

**Issue by shub12345** [yashagarwal1411/SubtitlesForYoutube#29]
How can I add subtitles to a video I am watching on YouTube and have it displayed using Chromecast. When I connect to chromecast the subtitles do not show on TV

**Comment by yasheltropy** [comment]
Not possible as per me. I had looked at the Chromecast API previously. This cannot be supported. Sorry.

**Comment by yashagarwal1411** [comment]
Not possible as per me. I had looked at the Chromecast API previously. This cannot be supported. Sorry.
