### ISSUE TITLE
IT NO LONGER WORKS 

### ISSUE THREAD

**Issue by minanagehsalalma** [yashagarwal1411/SubtitlesForYoutube#40]

**Comment by minanagehsalalma** [comment]
@yashagarwal1411 Whoa Great work mate 

I have an idea but i can't find an extension that does it 

Some times i come across videos with captions disabled and they are in unknown language

 i wasn't able to find a solution for this so here is what i thought 
 
 1. The extension downloads the video file as mp3 not mp4 
 2. the extension uses Microsoft speech to text to out put the subtitles into a srt file
 3. the extension loads the generated srt file 
 4. the extension allows translation of the subs if wanted through google translate 
 
 what do you think ?
 
 There is only sites that are capable of doing this but they take long long time

**Comment by MikeRidgway** [comment]
YTranslate.com does something like this but for a fee per minute.

**Comment by minanagehsalalma** [comment]
@MikeRidgway
Yeah most sites do it for a fee

But i come across a lot of videos with this problem
So i don't think doing it with a fee is feasible

Especially
That it can be done for free not that hard
