### ISSUE TITLE
Subtitles do not load in private window.

### ISSUE THREAD

**Issue by weisenhan** [yashagarwal1411/SubtitlesForYoutube#41]
Tried to pull confirmed subtitles from both opensubtitles and amara, but keep getting chrome-extension://oanhbddbfkjaphdibnebkklpplclomal/images/empty.svg error message.

Update: Automatically loads with regular windows.
Deselecting 'Automatically search and load subtitles in future' disables the extension or the UI.
v. 10.3.10

**Comment by sloanlance** [comment]
I had a similar problem.  The search runs, but finds the wrong subtitles.  See #42.

**Comment by weisenhan** [comment]
Did you get the wrong subtitles or any subtitles to load?
