### ISSUE TITLE
Fails to load subtitles

### ISSUE THREAD

**Issue by sloanlance** [yashagarwal1411/SubtitlesForYoutube#42]
I've recently added captions for a YouTube video, "The Wild Rover - Luke Kelly & The Dubliners" (https://www.youtube.com/watch?v=6DnR8v7X4zc).  The captions are in Amara (https://amara.org/videos/OAP67rT5Zzrw/info/the-wild-rover-luke-kelly-the-dubliners/) and opensubtitles.org (https://www.opensubtitles.org/en/subtitles/9459314/the-wild-rover-luke-kelly-the-dubliners-en).  This extension NEVER finds those captions.  I'd like someone to explain why.

This is similar to #41, but rather than saying the search is broken, I think the extension is trying the search, but it's not finding the right subtitles.  I say this because I was watching another video "Beer, Beer, Beer" (https://www.youtube.com/watch?v=yRzS1QakBt0) and the extension loaded subtitles, but they were for **_SOME OTHER VIDEO_**.  It was subtitles for "[OpenSub] Two.and.a.Half.Men.S12E12.HDTV.x264-LOL.srt" and many others that contained the word "Beer".

**Comment by yashagarwal1411** [comment]
Hi, I have fixed this issue in latest version 10.3.10
This was happening due to change in Amara endpoint for fetching subtitles info by Amara team
