### ISSUE TITLE
Amara subtitles do not display on private windows.

### ISSUE THREAD

**Issue by weisenhan** [yashagarwal1411/SubtitlesForYoutube#43]
Example from Readme.md https://www.youtube.com/watch?v=5qF_qbaWt3Q 
Doesn't display in private window but will in a regular window.
Chromium: 112.0.5615.121 Extension: 10.3.10

Works fine for opensubtitles in private windows.
Deselecting 'Automatically search and load subtitles in future' in the settings and refreshing causes the extension to be in a permanently disabled mode.

**Comment by yashagarwal1411** [comment]
Thanks for reporting this issue.
Fixed both issues in 10.4.20 

You should get the update in next 1-2 days.
